apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: authorino-metrics
  namespace: kuadrant-system
  labels:
    app.kubernetes.io/name: authorino
    app.kubernetes.io/part-of: mcp-observability
spec:
  selector:
    matchLabels:
      authorino-resource: authorino
      control-plane: controller-manager
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
  - port: http
    interval: 30s
    path: /server-metrics
