apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: github-mcp-server
  namespace: mcp-ecosystem
spec:
  parentRefs:
    - name: mcp-gateway
      namespace: mcp-system
      sectionName: mcps
  hostnames:
    - "github.mcp.<CLUSTER_DOMAIN>"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /mcp
      backendRefs:
        - name: github-mcp-server
          port: 8082
