apiVersion: mcp.kuadrant.io/v1alpha1
kind: MCPVirtualServer
metadata:
  name: user-tools
  namespace: mcp-system
spec:
  description: Basic read-only tools for developers
  tools:
    - openshift_namespaces_list
    - openshift_pods_get
    - openshift_pods_list
    - openshift_pods_list_in_namespace
    - openshift_pods_log
    - openshift_projects_list
    - openshift_resources_get
    - openshift_resources_list
