apiVersion: mcp.kuadrant.io/v1alpha1
kind: MCPVirtualServer
metadata:
  name: admin-tools
spec:
  description: All OpenShift and utility tools for admins
  tools:
    - openshift_pods_list
    - openshift_pods_get
    - openshift_pods_log
    - openshift_resources_list
    - openshift_resources_get
    - test_greet
    - test_time
