apiVersion: v1
kind: ConfigMap
metadata:
  name: gen-ai-aa-custom-model-endpoints
  namespace: workshop-playground
data:
  config.yaml: |
    providers:
      inference:
        - provider_id: endpoint-1
          provider_type: "remote::openai"
          config:
            base_url: "<MODEL_URL>"
            allowed_models:
              - "<MODEL_NAME>"
            custom_gen_ai:
              api_key:
                secretRef:
                  name: "endpoint-api-key-1"
                  key: "api_key"
    registered_resources:
      models:
        - provider_id: endpoint-1
          model_id: "<MODEL_NAME>"
          model_type: "llm"
          metadata:
            display_name: "External Model"
            custom_gen_ai:
              use_cases: "General purpose chat, tool calling, code generation"
